tackle = {"name": "Tackle", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True, "effect":""}
vine_whip = {"name": "Vine whip", "damage":40, "accuracy":100, "type":"grass", "inflict damage":True, "effect":""}
ember = {"name": "Ember", "damage":40, "accuracy":100, "type":"fire", "inflict damage":True, "effect":""}
water_gun = {"name": "Water gun", "damage":40, "accuracy":100, "type":"water", "inflict damage":True, "effect":""}
growl = {"name": "Growl", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"lower attack"}
quick_attack = {"name": "Quick attack", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True, "effect":""}
gust = {"name": "Gust", "damage":40, "accuracy":100, "type":"flying", "inflict damage":True, "effect":""}
sand_attack = {"name": "Sand attack", "damage":40, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"lower accuracy"}
pound = {"name": "Pound", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True, "effect":""}
defense_curl = {"name": "Defense curl", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"increase defence"}
double_slap = {"name": "Double slap", "damage":15, "accuracy":85, "type":"normal", "inflict damage":True, "effect":""}
poison_sting = {"name": "Poison Sting", "damage":15, "accuracy":100, "type":"poison", "inflict damage":True, "effect":""}
acid = {"name": "Acid", "damage":0, "accuracy":100, "type":"poison", "inflict damage":False, "effect":"inflict poison"}
bite = {"name": "Bite", "damage":40, "accuracy":100, "type":"dark", "inflict damage":True, "effect":""}
leer = {"name": "lLer", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"lower attack"}
string_shot = {"name": "String shot", "damage":0, "accuracy":95, "type":"bug", "inflict damage":False, "effect":"lower speed"}
bug_bite = {"name": "Bug bite", "damage":60, "accuracy":100, "type":"bug", "inflict damage":True, "effect":""}
double_team = {"name": "Double team", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"lower accuracy"}
thunder_wave = {"name": "Thunder wave", "damage":0, "accuracy":90, "type":"electric", "inflict damage":False, "effect":"inflict paralysis"}
thunder_shock = {"name": "Thunder shock", "damage":40, "accuracy":100, "type":"electric", "inflict damage":True, "effect":""}
tail_whip = {"name": "Tail whip", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False, "effect":"lower defence"}
dragon_breath = {"name": "Dragon breath", "damage":60, "accuracy":100, "type":"dragon", "inflict damage":True, "effect":""}
scratch = {"name": "Scratch", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True, "effect":""}
poison_powder = {"name": "Poison powder", "damage":0, "accuracy":75, "type":"poison", "inflict damage":False, "effect":"inflict poison"}
sing = {"name": "Sing", "damage":0, "accuracy":55, "type":"normal", "inflict damage":False, "effect":"inflict sleep"}

