tackle = {"name": "Tackle", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True}
vine_whip = {"name": "Vine whip", "damage":40, "accuracy":100, "type":"grass", "inflict damage":True}
ember = {"name": "Ember", "damage":40, "accuracy":100, "type":"fire", "inflict damage":True}
water_gun = {"name": "Water gun", "damage":40, "accuracy":100, "type":"water", "inflict damage":True}
growl = {"name": "Growl", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False}
quick_attack = {"name": "Quick attack", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True}
gust = {"name": "Gust", "damage":40, "accuracy":100, "type":"flying", "inflict damage":True}
sand_attack = {"name": "Sand attack", "damage":40, "accuracy":100, "type":"normal", "inflict damage":False}
pound = {"name": "Pound", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True}
defense_curl = {"name": "Defense curl", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False}
double_slap = {"name": "Double slap", "damage":15, "accuracy":85, "type":"normal", "inflict damage":True}
poison_sting = {"name": "Poison Sting", "damage":15, "accuracy":100, "type":"poison", "inflict damage":True}
acid = {"name": "Acid", "damage":0, "accuracy":100, "type":"poison", "inflict damage":False}
bite = {"name": "Bite", "damage":40, "accuracy":100, "type":"dark", "inflict damage":True}
leer = {"name": "lLer", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False}
string_shot = {"name": "String shot", "damage":0, "accuracy":95, "type":"bug", "inflict damage":False}
bug_bite = {"name": "Bug bite", "damage":60, "accuracy":100, "type":"bug", "inflict damage":True}
double_team = {"name": "Double team", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False}
thunder_wave = {"name": "Thunder wave", "damage":0, "accuracy":90, "type":"electric", "inflict damage":False}
thunder_shock = {"name": "Thunder shock", "damage":40, "accuracy":100, "type":"electric", "inflict damage":True}
tail_whip = {"name": "Tail whip", "damage":0, "accuracy":100, "type":"normal", "inflict damage":False}
dragon_breath = {"name": "Dragon breath", "damage":60, "accuracy":100, "type":"dragon", "inflict damage":True}
scratch = {"name": "Scratch", "damage":40, "accuracy":100, "type":"normal", "inflict damage":True}
poison_powder = {"name": "Poison powder", "damage":0, "accuracy":75, "type":"poison", "inflict damage":False}
sing = {"name": "Sing", "damage":0, "accuracy":55, "type":"normal", "inflict damage":False}

