import moves

bulbasaur = {"name": "Bulbasaur", "level": 5, "type": "grass", "max_health": 45, "current_health": 45, "attack": 49, "defence": 49, "speed": 45, "knocked_out": False, "xp": 0, "move1": moves.tackle, "move2": moves.vine_whip, "move3": moves.growl, "move4": moves.poison_powder}
charmander = {"name": "Charmander", "level": 5, "type": "fire", "max_health": 39, "current_health": 39, "attack": 52, "defence": 43, "speed": 65, "knocked_out": False, "xp": 0, "move1": moves.scratch, "move2": moves.ember, "move3": moves.growl, "move4": moves.dragon_breath}
squirtle = {"name": "Squirtle", "level": 5, "type": "water", "max_health": 44, "current_health": 44, "attack": 48, "defence": 65, "speed": 43, "knocked_out": False, "xp": 0, "move1": moves.tackle, "move2": moves.water_gun, "move3": moves.tail_whip, "move4": moves.bite}
rattata = {"name": "Rattata", "level": 5, "type": "normal", "max_health": 30, "current_health": 30, "attack": 56, "defence": 35, "speed": 72, "knocked_out": False, "xp": 0, "move1": moves.tackle, "move2": moves.tail_whip, "move3": moves.quick_attack, "move4": moves.bite}
pikachu = {"name": "Pikachu", "level": 5, "type": "electric", "max_health": 35, "current_health": 35, "attack": 55, "defence": 40, "speed": 90, "knocked_out": False, "xp": 0, "move1": moves.thunder_shock, "move2": moves.thunder_wave, "move3": moves.growl, "move4": moves.double_team}
caterpie = {"name": "Caterpie", "level": 5, "type": "bug", "max_health": 45, "current_health": 45, "attack": 30, "defence": 35, "speed": 45, "knocked_out": False, "xp": 0, "move1": moves.tackle, "move2": moves.bug_bite, "move3": moves.string_shot, "move4": moves.tackle}
ekans = {"name": "Ekans", "level": 5, "type": "poison", "max_health": 35, "current_health": 35, "attack": 60, "defence": 44, "speed": 55, "knocked_out": False, "xp": 0, "move1": moves.poison_sting, "move2": moves.acid, "move3": moves.bite, "move4": moves.leer}
jigglypuff = {"name": "Jigglypuff", "level": 5, "type": "fairy", "max_health": 115, "current_health": 115, "attack": 45, "defence": 20, "speed": 20, "knocked_out": False, "xp": 0, "move1": moves.sing, "move2": moves.pound, "move3": moves.defense_curl, "move4": moves.double_slap}
pidgey = {"name": "Pidgey", "level": 5, "type": "flying", "max_health": 40, "current_health": 40, "attack": 45, "defence": 40, "speed": 56, "knocked_out": False, "xp": 0, "move1": moves.tackle, "move2": moves.sand_attack, "move3": moves.gust, "move4": moves.quick_attack}

